name: "Create Release"
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump-semver.outputs.new_version }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get-latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1

      - name: Bump version
        id: bump-semver
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch

  build-modpack:
    name: Build Minecraft Modpack
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Setup pakku
        run: |
          wget https://github.com/juraj-hrivnak/Pakku/releases/download/v0.21.0/pakku.jar
      - name: Export modpack
        run: java -jar pakku.jar export
      - name: 'Upload Curseforge Build Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: curseforge-artifact
          path: ./build/curseforge/
          retention-days: 5
      - name: 'Upload Server Build Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: server-artifact
          path: ./build/serverpack/
          retention-days: 5

  release-modpack:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-modpack, get-version]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download the curseforge artifact
        uses: actions/download-artifact@v4
        with:
          name: curseforge-artifact
          path: ./curseforge-artifact
      - name: Download the server artifact
        uses: actions/download-artifact@v4
        with:
          name: server-artifact
          path: ./server-artifact
      - name: Extract Artifacts
        run: |
          mkdir -p ./curseforge
          unzip ./curseforge-artifact/Lively\ Coggers-*.zip -d ./curseforge
          mkdir -p ./server
          unzip ./server-artifact/Lively\ Coggers-*.zip -d ./server
      - name: Zip Curseforge Directory
        run: zip -r curseforge-${{ needs.get-version.outputs.new_version }}.zip ./curseforge/* ./curseforge/.*  # Include hidden files
      - name: Zip Server Directory
        run: zip -r server-${{ needs.get-version.outputs.new_version }}.zip ./server/* ./server/.*  # Include hidden files
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-tag: ${{ needs.get-version.outputs.new_version }}
          github-generate-changelog: true
          github-draft: true
          github-prerelease: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            curseforge-${{ needs.get-version.outputs.new_version }}.zip
            server-${{ needs.get-version.outputs.new_version }}.zip
          name: Lively Coggers ${{ needs.get-version.outputs.new_version }}
          version: ${{ needs.get-version.outputs.new_version }}
          version-type: prerelease
          changelog-file: CHANGELOG.*
          loaders: forge
          game-versions: 1.20.1