name: Upload modpack to pterodactyl
on: 
    workflow_dispatch:

jobs:
    Build-Minecraft-Modpack:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v2
              with:
                  distribution: 'adopt'
                  java-version: '21'
            - name: Setup pakku
              run: |
                  wget https://github.com/juraj-hrivnak/Pakku/releases/download/v0.21.0/pakku.jar
            - name: Export modpack
              run: java -jar pakku.jar export
            - name: Upload files to Pterodactyl
              uses: rexlManu/pterodactyl-upload-action@v2.4
              with:
                panel-host: ${{ secrets.PTERODACTYL_SERVER }}
                api-key: ${{ secrets.PTERODACTYL_API_KEY }}
                server-id: ${{ secrets.PTERODACTYL_SERVER_ID }}
                source: ./build/serverpack/*
                target: "./test/"
                decompress-target: true